# Create a Status named 'Required' that reports the observed conclusion of all
# matching WorkflowRuns on the same `head_sha` as the observed WorkflowRun.
name: Required

on:
  workflow_run:
    workflows:
      - Check Transpiled JavaScript
      - Continuous Integration
      - Lint Codebase
    types:
      - completed

jobs:
  success:
    if: contains(fromJSON('["merge_group", "pull_request"]'), github.event.workflow_run.event)
    name: Create appropriate status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          status-name: Required
          must-succeed-if-run: |
            Check Transpiled JavaScript
            Continuous Integration
            Lint Codebase
