name: Optional required workflows
description: >-
  Configure required workflows in your repository. Use path filters. Leave your
  GitHub org administrator alone.
author: jnewland@urcomputeringpal.com
# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'check-circle'
  color: 'green'

# Define your inputs here.
inputs:
  token:
    description: >-
      Token to use to lookup workflow runs. Requires `actions: read`
      permissions.
    required: true
  status-name:
    description: >
      The status name use for reporting. You should mark this as required.
    required: true
  must-succeed-if-run:
    description: >
      A multi-line string of the names of workflows that must succeed if a run
      is observed.
    required: true

runs:
  using: node20
  main: dist/index.js
