name: Required

on:
  workflow_run:
    workflows:
      # Add workflows here to mark them as required if observed on pull request
      # or merge group events. If any of them fail, the a failing status will
      # be created. At least one of these workflows must succeed for this
      # workflow to succeed.
      #
      # Workflows in this list **may** use `paths` to match only run when
      # certain files or directories change. As opposed to the traditional
      # required status setting on GitHub repositories, a PR will not be
      # blocked if it skips a workflow in this list.
      #
      # !!! IMPORTANT !!! ##
      # This list must match the list passed to must-succeed-if-run argument
      # at the end of this workflow file
      #
      - Check Transpiled JavaScript
      - Continuous Integration
      - Lint Codebase
    types:
      - completed

permissions:
  contents: read
  actions: read
  statuses: write

run-name: >
  Process ${{ github.event.workflow_run.conclusion }} of ${{
  github.event.workflow_run.name }}

jobs:
  status:
    if:
      contains(fromJSON('["merge_group", "pull_request"]'),
      github.event.workflow_run.event)
    name: Create status summarizing conclusion of required workflows
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      statuses: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          status-name: Required
          # !!! IMPORTANT !!! ##
          # This list must match the list passed to on.workflow_run.workflows
          must-succeed-if-run: |
            Check Transpiled JavaScript
            Continuous Integration
            Lint Codebase
